### ISSUE TITLE
Errors on server start + join

### ISSUE THREAD

**Issue by TheTechPny** [Partonetrain/iafgear#9] opened 2021-07-16 14:29 UTC
## Versions

- **Silent Gear**: silent-gear-1.16.5-2.6.30.jar
- **Silent's Gems**: No
- **Silent Lib**: silent-lib-1.16.3-4.9.6.jar
- **Forge**: forge-1.16.5-36.1.32.jar
- **Modpack**: The 2b2m Modpack
- **Optifine Installed**: No 

## Links/Images
https://pastebin.com/raw/SbripbWN
https://imgur.com/a/CF1fnEv

**Comment by Partonetrain** [comment] 2021-07-17 17:48
Duplicate of #8

**Closed as completed by Partonetrain** 2021-07-17 17:48 UTC
